// Generated by Wrangler by running `wrangler types`

interface Env {
	DEMO_USERNAME: string;
	DEMO_PASSWORD: string;
	PRE_SHARED_KEY: string;
	WEBSOCKET_SERVER: DurableObjectNamespace<import("./src/index").WebSocketServer>;
	QUEUE: Queue;
	ASSETS: Fetcher;
}
